- name: catalogue configure
  hosts: catalogue
  become: yes

  tasks:

  - name: disable nodejs
    ansible.builtin.command: dnf module enable nodejs:20 -y
  
  - name: install nodejs
    ansible.builtin.dnf:
      name: nodejs
      state: present
    
  - name: 
    ansible.builtin.user:
          name: roboshop
          comment: "roboshop system user"
          system: true      # This flag designates it as a system user (lower UID, no default home/shell)
          shell: /sbin/nologin # Assign a no-login shell for security
          home: /app # Prevents creating a home directory
          state: present

  - name: Create a directory if it does not exist
    ansible.builtin.file:
      path: /app
      state: directory
  
  - name: Download the application archive
    ansible.builtin.get_url:
        url: https://roboshop-artifacts.s3.amazonaws.com/catalogue-v3.zip 
        dest: /tmp/catalogue.zip
        
  -  name: unarhive application
     ansible.builtin.unarchive:
        src: /tmp/catalogue.zip
        dest: /app
        remote_src: yes

  - name: Install packages based on package.json.
    community.general.npm:
      path: /app

  - name: Copy  catalogue service file
    ansible.builtin.copy:
      src: catalogue.service
      dest: /etc/systemd/system/catalogue.service

  - name: copy mongo repo
    ansible.builtin.copy:
      src: mongo.repo
      dest: /etc/yum.repos.d/mongo.repo

  - name: install mongodb client
    ansible.builtin.dnf:
      name: mongodb-mongosh
      state: present

  - name: check products loaded
    ansible.builtin.command: mongosh --host "{{ MONGODB_HOST }}" --quiet  --eval 'db.getMongo().getDBNames().indexOf("catalogue")'
    register: catalogue_output

  - name: print the output
    ansible.builtin.debug:
      msg: "{{ catalogue_output }}"

  - name: load the products
    ansible.builtin.shell: mongosh --host "{{ MONGODB_HOST }}" </app/db/master-data.js
    when: catalogue_output.stdout  | int < 0

  - name: start catalogue
    ansible.builtin.service:
      name: catalogue
      state: restarted
      enabled: yes