- name: configure user service
  hosts: user
  become: yes


  tasks:

  - name: enable nodejs
    ansible.builtin.command: dnf module enable nodejs:20 -y


  - name: install nodejs
    ansible.builtin.dnf:
      name: nodejs
      state: present

  - name: create system user
    ansible.builtin.user:
      name: roboshop
      comment: "roboshop system user"
      shell: /sbin/nologin
      home: /app
      system: true

  - name: delete app directory
    ansible.builtin.file:
      path: /app
      state: absent 

  - name: create app directory
    ansible.builtin.file:
      path: /app
      state: directory

  - name: delete user zip file
    ansible.builtin.file:
      path: /tmp/user.zip
      state: absent
  
  - name: download user zip file
    ansible.builtin.get_url:
      url: https://roboshop-artifacts.s3.amazonaws.com/user-v3.zip
      dest: /tmp/user.zip

  - name: unarchive user
    ansible.builtin.unarchive:
      src: /tmp/user.zip
      dest: /app

  - name: install npm 
    ansible.community.npm:
      path: /app
  
  - name: copy user service
    ansible.builtin.template:
      src: user.service
      dest: /etc/systemd/system/user.service

  - name: daemon reload
    ansible.builtin.systemd_service:
      daemon_reload: true

  - name: start user
    ansible.builtin.service:
      name: user
      state: restarted
      enabled: yes